FROM public.ecr.aws/lambda/python:3.9

# Set the working directory to /var/task
WORKDIR /var/task

# Copy function code and requirements
COPY v2.py ${LAMBDA_TASK_ROOT}
COPY requirements.txt .

# Install the specified packages
RUN pip install --no-cache-dir -r requirements.txt

# Set the CMD to your handler
CMD ["v2.lambda_handler"]